version: '3.8'
  services:
    db:
      image: postgres:latest
      environment:
        POSTGRES_DB: library_db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    web:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db